name: Cause Inspired Media
favicon: null
layout_spectrum: 0
typography_spectrum: 0.38697
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#20a7c1'
    - '#2b3c73'
    - '#242020'
    - '#000000'
    - '#00bfbf'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
