name: Cause Inspired Media
favicon: null
layout_spectrum: 1
typography_spectrum: 0.56716
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#20a7c1'
    - '#2b3c73'
    - '#242020'
    - '#000000'
    - '#00bfbf'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.1285898711066693
purpose: []
